/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'

const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/ofertas': typeof OfertasRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/ofertas': typeof OfertasRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/ofertas': typeof OfertasRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesorios'
    | '/carrito'
    | '/checkout'
    | '/ofertas'
    | '/pedido/$id'
    | '/producto/$slug'
    | '/api/public/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesorios'
    | '/carrito'
    | '/checkout'
    | '/ofertas'
    | '/pedido/$id'
    | '/producto/$slug'
    | '/api/public/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/accesorios'
    | '/carrito'
    | '/checkout'
    | '/ofertas'
    | '/pedido/$id'
    | '/producto/$slug'
    | '/api/public/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoriosRoute: typeof AccesoriosRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  OfertasRoute: typeof OfertasRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoriosRoute: AccesoriosRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  OfertasRoute: OfertasRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
